### ISSUE TITLE
Submenu Resultados esperados - Apresentar lista de todos os domínios ao clicar em Forças ou Fraquezas

### ISSUE THREAD

**Issue by kjoao** [lutonda/Everest4.0-server#67]
Resultados esperados - Apresentar lista de todos os domínios ao clicar em Forças ou Fraquezas

Ao clicar em forças e fraquezas, a aplicação deve apresentar todos os domínios (Pessoal, Profissional e Financeiro), mas em cada um deles, apresentar apenas as variáveis que representam forças ou fraquezas. Ou seja, os domínios devem ser fixos, as as variáveis é que devem ir alterando, conforme forem forças ou fraquezas.

A aplicação deve permitir que o utilizador faça carregamento de objectivos para domínios que não tenham forças ou fraquezas. Ou seja, o ecrã de carregamento de objectivos e metas deve estar disponível para todos domínios, independentemente se têm ou não forças e fraquezas.

**Comment by lutonda** [comment]
Preciso de uma overview sobre este requisito/funcionalidade
