### ISSUE TITLE
Menu Início  - Agenda e pendentes e tarefas - Opção para listagem

### ISSUE THREAD

**Issue by kjoao** [lutonda/Everest4.0-server#72]
Para evitar ter uma lista longa de agendas e pendentes, tarefas em atraso e tarefas da semana, encontrar um mecanismo de listar no máximo 5 compromissos, 5 tarefas em atraso e 5 tarefas da semana, adicionando uma opção, em cada um, com o total e a possibilidade de ao clicar nesse total o utilizador ver os restantes compromissos e tarefas.

**Comment by kjoao** [comment]
Ao apresentar a listagem dos compromissos, tarefas em atraso e tarefas da semana, a aplicação deve organiza-las por ordem de Prioridade: Alta, Média e Baixa. 

A classificação por prioridade deve seguir as seguintes regras:
- Prioridade Baixa: Compromissos e tarefas que não estão associados a nenhum objectivo.
- Prioridade Média: Compromissos e tarefas que estão associados a objectivos, mas cuja data de conclusão (do compromisso ou tarefa) é a semana seguinte.
- Prioridade Alta: Compromissos e tarefas que estão associados a objectivos, cuja data de conclusão (do compromisso ou tarefa) é a semana corrente (semana actual).

**Comment by lutonda** [comment]
> Ao apresentar a listagem dos compromissos, tarefas em atraso e tarefas da semana, a aplicação deve organiza-las por ordem de Prioridade: Alta, Média e Baixa.
> 
> A classificação por prioridade deve seguir as seguintes regras:
> 
> * Prioridade Baixa: Compromissos e tarefas que não estão associados a nenhum objectivo.
> * Prioridade Média: Compromissos e tarefas que estão associados a objectivos, mas cuja data de conclusão (do compromisso ou tarefa) é a semana seguinte.
> * Prioridade Alta: Compromissos e tarefas que estão associados a objectivos, cuja data de conclusão (do compromisso ou tarefa) é a semana corrente (semana actual).

Gerado um novo Issue
