### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by lutonda** [lutonda/Everest4.0-server#94]
https://demos.creative-tim.com/paper-kit-2-angular/#/home

**Comment by kjoao** [comment]
Criar web site www.everest40.com

Estrutura do website:
1. Institucional
 A Everest LDA Consultoria e Gestão de Carreiras é uma empresa de consultoria online em planeamento estratégico pessoal, desenvolvimento e gestão de carreiras.
 Missão (colar a imagem consta no documento em anexo).
Visão (colar a imagem consta no documento em anexo).
Valores (colar a imagem consta no documento em anexo).

2. Serviços 
Nossos serviços são disponibilizados através do aplicativo Everest 4.0 e incluem:
- Planeamento estratégico pessoal: apoio na análise estratégica nos 3 pilares da vida (Pessoal, Profissional e Financeiro), mediante a identificação das Forças, Fraquezas, Oportunidades e Ameaças, bem como apoio na definição de objectivos, estratégias, planos de acções e orçamento para alcançar as metas. 
- Desenvolvimento de competências: apoio no diagnóstico de competências necessárias ao alcance dos objectivos definidos, elaboração, execução e avaliação da eficácia do plano de desenvolvimento de competências;
- Gestão de carreiras: apoio no diagnóstico e planeamento estratégico profissional, elaboração e execução de planos de acção para quem pretende entrar no mercado de trabalho (primeiro emprego) ou a procura de novos desafios (mobilidade ou promoção), preparando e acompanhando o cliente em todas as fases do processo;
- Comunidade Everest (networking): através da qual o cliente podem interagir com outros profissionais e ampliar sua rede de contactos; 
- Outros serviços: Anúncio de vagas de emprego, cursos online e coaching online. 

3. Everest 4.0
O Everest 4.0 é o aplicativo pelo qual prestamos o nossos serviços.  É possível utilizar muitas funcionalidades do aplicativo mesmo quando não estiver conectado à internet. Assista o vídeo abaixo para conhecer mais sobre o aplicativo e suas principais funcionalidades, incluindo as que estão disponíveis offline. 

   Planos e preços 
   (colar a imagem consta no documento em anexo).

Aplicativo disponível no Google Play e na App Store 

4. Anúncio de vagas de emprego 

Os utilizadores da nossa aplicação são pessoas comprometidas em melhorar o seu desempenho tanto pessoal como profissional. Nos na Everest apoiamos os nossos clientes no alcance desse propósito. 
Por isso, temos a disposição das empresas e instituições uma base de dados com melhores candidatos do mercado para responder às necessidades de pessoal. 
Anuncie aqui as suas vagas e encontre os melhores candidatos. 
(Incluir uma Ficha online para anúncio anúncio de vagas. Uma vaga registada no site deve aparecer automaticamente na aplicação num submódulo "Vagas de emprego" do módulo "Vagas de emprego e gestão de carreiras")

5. Apoio ao cliente

**Comment by kjoao** [comment]
Para mais informação, ver documento em anexo.

[Everest LDA - Consultoria e Gestão de Carreiras - Apresentação do Projecto - Resumo Executivo.pdf](https://github.com/lutonda/Everest4.0-server/files/5720012/Everest.LDA.-.Consultoria.e.Gestao.de.Carreiras.-.Apresentacao.do.Projecto.-.Resumo.Executivo.pdf)

**Comment by kjoao** [comment]
E-mail já existente:
everest40lda@gmail.com <everest40lda@gmail.com>

Contudo, pode-se criar um email com o domínio do site.
